name: running go test

on:
  push:
  workflow_dispatch:

jobs:
  goTest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: docker.io/postgres:17.2-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: rootkit
          POSTGRES_DB: magicplatform_db
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'
      - name: Test with the Go CLI
        run: go test -tags=all -count 1 -json ./...